apiVersion: v1
kind: Namespace
metadata:
  name: vlaanderen
  labels:
    name: vlaanderen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loonsimulatie-frontend
  namespace: vlaanderen
spec:
  selector:
    matchLabels:
      app: loonsimulatie-frontend
  template:
    metadata:
      labels:
        app: loonsimulatie-frontend
    spec:
      containers:
      - name: loonsimulatie-frontend
        image: ghcr.io/xunafay/loonsimulatie-laravel-frontend:main
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3000
          name: http
      imagePullSecrets:
      - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: loonsimulatie-frontend
  namespace: vlaanderen
spec:
  selector:
    app: loonsimulatie-frontend
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loonsimulatie-frontend-ingress
  namespace: vlaanderen
  annotations:
    cert-manager.io/cluster-issuer: prod-issuer
spec:
  ingressClassName: haproxy
  rules:
  - host: nuxtjs.loonsimulatie.hexodine.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loonsimulatie-frontend
            port:
              number: 80
  tls:
  - hosts:
    - nuxtjs.loonsimulatie.hexodine.com
    secretName: loonsimulatie-nuxtjs-cert
