apiVersion: v1
kind: Namespace
metadata:
  name: vlaanderen
  labels:
    name: vlaanderen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loonsimulatie-backend
  namespace: vlaanderen
spec:
  selector:
    matchLabels:
      app: loonsimulatie-backend
  template:
    metadata:
      labels:
        app: loonsimulatie-backend
    spec:
      containers:
      - name: loonsimulatie-backend
        image: ghcr.io/xunafay/loonsimulatie-laravel-backend:main
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: APP_DEBUG
          value: "true"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: key
        - name: DB_CONNECTION
          value: pgsql
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: laravel
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: password
        ports:
        - containerPort: 80
          name: http
      - name: posgresql
        image: postgres:13
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        env:
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_DB
          value: laravel
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pvc
  namespace: vlaanderen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: loonsimulatie-backend
  namespace: vlaanderen
spec:
  selector:
    app: loonsimulatie-backend
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 5432
    targetPort: 5432
    name: postgres
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loonsimulatie-backend-ingress
  namespace: vlaanderen
  annotations:
    cert-manager.io/cluster-issuer: prod-issuer
spec:
  ingressClassName: haproxy
  rules:
  - host: api.loonsimulatie.hexodine.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loonsimulatie-backend
            port:
              number: 80
  tls:
  - hosts:
    - api.loonsimulatie.hexodine.com
    secretName: loonsimulatie-laravel-cert
